# Generated by Django 3.0.1 on 2020-06-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_is', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_is', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_group_owner', related_query_name='group', to='person.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_is', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_is', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('question', models.TextField(blank=True)),
                ('question_is', models.TextField(blank=True, null=True)),
                ('question_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('timed', models.BooleanField(default=False)),
                ('time_allowed', models.SmallIntegerField(default=120, help_text='Sekúndur')),
                ('single_selection', models.BooleanField(default=False)),
                ('points', models.SmallIntegerField(default=5)),
                ('hint', models.TextField(blank=True)),
                ('hint_is', models.TextField(blank=True, null=True)),
                ('hint_en', models.TextField(blank=True, null=True)),
                ('hint_cost', models.SmallIntegerField(default=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group_correct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_correct', to='questions.Group')),
                ('group_false', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_false', to='questions.Group')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_question_owner', related_query_name='question', to='person.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_is', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_is', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_questionnaire_owner', related_query_name='questionnaire', to='person.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Group')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Group')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_is', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_is', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('answer', models.CharField(max_length=300)),
                ('correct', models.BooleanField(default=False)),
                ('value_from', models.FloatField(default=0.0)),
                ('value_to', models.FloatField(default=0.0)),
                ('correct_value_from', models.FloatField(default=0.0)),
                ('correct_value_to', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_option_owner', related_query_name='option', to='person.Person')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
