# Generated by Django 3.0.1 on 2020-06-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description_is',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_is',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='description_is',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='name_is',
        ),
        migrations.AddField(
            model_name='option',
            name='answer_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='answer_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='answer_is',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_de',
            field=models.TextField(blank=True, null=True),
        ),
    ]
