# Generated by Django 3.0.1 on 2020-06-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_squashed_0008_auto_20200605_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_option', related_query_name='question_option_option', to='questions.Question'),
        ),
    ]
