# Generated by Django 3.0.1 on 2020-06-04 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200604_2119'),
        ('questions', '0002_auto_20200604_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_group_owner', related_query_name='group', to='person.PersonUser'),
        ),
        migrations.AlterField(
            model_name='option',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_option_owner', related_query_name='option', to='person.PersonUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_question_owner', related_query_name='question', to='person.PersonUser'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_questionnaire_owner', related_query_name='questionnaire', to='person.PersonUser'),
        ),
    ]
