# Generated by Django 3.0.1 on 2020-06-04 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200604_2119'),
        ('questions', '0004_auto_20200604_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_option_owner', related_query_name='option_owner', to='person.PersonUser'),
        ),
    ]
