# Generated by Django 3.0.1 on 2020-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200605_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ManyToManyField(blank=True, to='questions.Group'),
        ),
    ]
