# Generated by Django 3.0.1 on 2020-06-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200604_2119'),
        ('questions', '0005_auto_20200604_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_option', related_query_name='question_option_option', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_question_owner', related_query_name='question_owner', to='person.PersonUser'),
        ),
    ]
