# Generated by Django 3.0.1 on 2020-06-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200604_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='option',
            name='question_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_option', related_query_name='question_option_option', to='questions.Question'),
            preserve_default=False,
        ),
    ]
