# Generated by Django 3.0.1 on 2020-11-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_testanswers_testmemo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiongrouprelation',
            options={'verbose_name': ('tengd spurning',), 'verbose_name_plural': 'tengdar spurningar'},
        ),
        migrations.AddField(
            model_name='testmemo',
            name='known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testmemo',
            name='not_known',
            field=models.BooleanField(default=True),
        ),
    ]
