# Generated by Django 3.0.1 on 2020-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200604_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='time_allowed',
            field=models.SmallIntegerField(default=120, help_text='Mínútur'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='timed',
            field=models.BooleanField(default=False),
        ),
    ]
