# Generated by Django 3.0.1 on 2020-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20201112_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmemo',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
