# Generated by Django 3.0.1 on 2020-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_testmemo_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswers',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='description_is',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='name_is',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testmemo',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testmemo',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testmemo',
            name='description_is',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testmemo',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testmemo',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testmemo',
            name='name_is',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
