# Generated by Django 3.0.1 on 2020-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20201116_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmemo',
            name='difficulty',
            field=models.SmallIntegerField(default=5),
        ),
    ]
