# Generated by Django 3.0.1 on 2020-11-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_testmemo_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmemo',
            old_name='not_known',
            new_name='archive',
        ),
    ]
