# Generated by Django 3.0.1 on 2020-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20201117_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswers',
            name='time_taken',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
