# Generated by Django 3.0.1 on 2020-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_testanswers_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='question',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
