# Generated by Django 3.0.1 on 2020-11-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_remove_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='question_collection',
            field=models.ManyToManyField(blank=True, to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='category',
            name='question',
            field=models.ManyToManyField(blank=True, to='questions.Question'),
        ),
    ]
