# Generated by Django 3.0.1 on 2020-11-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_questionnaire_question_collection_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='question_collection_str',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
