# Generated by Django 3.0.1 on 2020-11-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20201119_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswers',
            name='test_practice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questions.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='omit_known',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='time_allowed',
            field=models.SmallIntegerField(blank=True, default=120, help_text='Mínútur'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='timed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
