# Generated by Django 3.0.1 on 2020-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20201120_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswers',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testanswers',
            name='options_ids',
            field=models.CharField(default='', max_length=200),
        ),
    ]
