# Generated by Django 3.0.1 on 2020-11-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200604_2119'),
        ('questions', '0022_auto_20201120_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['?'], 'verbose_name': ('svar',), 'verbose_name_plural': 'svör'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['?'], 'verbose_name': ('spurning',), 'verbose_name_plural': 'spurningar'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='only_failed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='timed',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.SmallIntegerField(choices=[[0, 'Failed'], [1, 'Correct'], [2, 'Omitted']], default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questionnaire')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.PersonUser')),
            ],
        ),
    ]
