# Generated by Django 3.0.1 on 2020-11-26 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_questionnaireresults_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswers',
            name='points_given',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='question',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.PROTECT, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='result',
            field=models.SmallIntegerField(choices=[[0, 'Failed'], [1, 'Correct'], [2, 'Omitted']], default=0),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='result_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestionnaireResults',
        ),
    ]
