# Generated by Django 3.0.1 on 2020-11-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200604_2119'),
        ('questions', '0025_auto_20201126_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanswers',
            name='time_allowed',
        ),
        migrations.RemoveField(
            model_name='testanswers',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='testanswers',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='testanswers',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='testanswers',
            name='known',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_questionnaire_owner', related_query_name='questionnaire', to='person.PersonUser'),
        ),
        migrations.AlterField(
            model_name='testanswers',
            name='question',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='testanswers',
            name='test_practice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Questionnaire'),
        ),
    ]
