# Generated by Django 3.0.1 on 2020-11-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20201126_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswers',
            name='postpone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testanswers',
            name='result',
            field=models.SmallIntegerField(choices=[[-1, 'Failed'], [0, 'Omitted'], [1, 'Correct']], default=0),
        ),
    ]
