# Generated by Django 3.0.1 on 2020-11-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_auto_20201126_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmemo',
            name='question',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='testanswers',
            name='result',
            field=models.SmallIntegerField(choices=[[-1, 'Failed'], [0, 'Postponed'], [1, 'Correct']], default=0),
        ),
    ]
