# Generated by Django 3.0.1 on 2020-12-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20201127_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questions.Category'),
        ),
    ]
