# Generated by Django 3.0.1 on 2020-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20201214_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_question',
            field=models.BooleanField(default=False),
        ),
    ]
