# Generated by Django 3.0.1 on 2021-01-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_question_exam_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='single_selection',
            field=models.BooleanField(default=True),
        ),
    ]
