# Generated by Django 3.0.1 on 2021-01-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_auto_20210107_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='practice',
            field=models.BooleanField(default=True),
        ),
    ]
