# Generated by Django 3.0.1 on 2021-01-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_questionnaire_practice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', '?'], 'verbose_name': ('spurning',), 'verbose_name_plural': 'spurningar'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
