# Generated by Django 3.0.1 on 2021-01-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20201215_1137'),
        ('questions', '0033_auto_20210114_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': ('flokkur',), 'verbose_name_plural': 'flokkar'},
        ),
        migrations.RemoveField(
            model_name='testanswers',
            name='tesing_user',
        ),
        migrations.AddField(
            model_name='testanswers',
            name='tesing_user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='person.PersonUser'),
        ),
    ]
