# Generated by Django 3.0.1 on 2021-01-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_auto_20210114_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testanswers',
            options={'ordering': ['test_practice', 'created_date'], 'verbose_name': ('svar á prófi',), 'verbose_name_plural': 'svör á prófum'},
        ),
        migrations.AddField(
            model_name='question',
            name='flipcard_question',
            field=models.BooleanField(default=False),
        ),
    ]
