# Generated by Django 3.0.1 on 2021-01-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_questionsandanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsandanswers',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionsandanswers',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionsandanswers',
            name='description_is',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionsandanswers',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionsandanswers',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionsandanswers',
            name='name_is',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionsandanswers',
            name='topic',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
