# Generated by Django 3.0.1 on 2021-01-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_textblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='order',
            field=models.IntegerField(default=0, help_text='Röð á svæði, númer: 0…n'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='spot',
            field=models.SmallIntegerField(default=0, help_text='Svæði,  '),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='slot',
            field=models.CharField(help_text='Heiti á hólfi, samfellt og án sértákna, lágstafir', max_length=100),
        ),
    ]
