# Generated by Django 3.0.1 on 2021-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_auto_20210121_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='spot',
            field=models.SmallIntegerField(choices=[[1, 'Carousel'], [2, 'Kubbar'], [3, 'Um vefinn'], [3, 'Um Q&A'], [3, 'Fyrirvarar'], [3, 'Skilmálar'], [3, 'Áskrift']], default=0, help_text='Svæði,  '),
        ),
    ]
