# Generated by Django 3.0.1 on 2021-03-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_auto_20210126_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='answered_questions',
            field=models.SmallIntegerField(default=0),
        ),
    ]
