# Generated by Django 3.0.1 on 2021-03-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_questionnaire_answered_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
