# Generated by Django 3.0.1 on 2021-03-30 10:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_textblock_icon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='text_to_display',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
