# Generated by Django 3.0.1 on 2021-03-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0045_auto_20210330_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='option',
            name='description_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='description_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='questionsandanswers',
            name='description_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='testanswers',
            name='description_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='testmemo',
            name='description_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='description_wysiwyg',
        ),
    ]
