# Generated by Django 3.0.1 on 2021-03-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0046_auto_20210331_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='icon_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
