# Generated by Django 3.0.1 on 2021-03-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0047_auto_20210331_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='urlpath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
