# Generated by Django 3.0.1 on 2021-04-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0048_textblock_urlpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_class',
            field=models.CharField(default='', max_length=200),
        ),
    ]
