# Generated by Django 3.0.1 on 2020-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('kt', models.CharField(blank=True, max_length=10, null=True)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.SmallIntegerField(default=0)),
                ('admin_note', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_ptr',
        ),
    ]
