# Generated by Django 3.0.1 on 2021-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20201215_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='personuser',
            name='prefs_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personuser',
            name='prefs_system_dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
