# Generated by Django 3.0.1 on 2021-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20210128_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='personuser',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personuser',
            name='picture',
            field=models.ImageField(default='None', upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
